### ISSUE TITLE
Error when archiving

### ISSUE THREAD

**Issue by fizzyade** [patr0nus/libnode#1]
I successfully built the library and have tested that the example compiles and returns 0, all good.

The final stages of archiving though I get the following error:

`Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/adriancarpenter/Downloads/libnode-master/scripts/postproc.py", line 57, in <module>
    shutil.copytree(os.path.join(nodeSrcFolder, 'include'), os.path.join(resultFolder, 'include'))
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'node-v14.13.1/include'
libnode-v14.13.1-darwin-x64-nointl.zip`

Is this a compatibility error with my system?  I'm on the latest Catalina.

**Comment by fizzyade** [comment]
I used a copytree function that provides the ability to set included files and pointed it at the src folder rather than src/includes and that fixes the issue.

I don't know whether the layout of the source has changed since the last update of this script, but the script uses src/includes but in the latest version the include files are in the src folder, hence the need for the filtered copy tree to avoid coping anything else other than header files.

**Comment by kuyoonjo** [comment]
Same here. The solution is running `python3 -m scripts.headers` before `python3 -m scripts.postproc`. @patr0nus
